name: CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '*.md'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - uses: crystal-lang/install-crystal@v1
      with:
        crystal: 1.17.1

    - name: Install dependencies
      run: shards install

    - name: Run tests
      run: make test
