name: CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '*.md'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Add Crystal repos
      run: curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash

    - name: Install crystal
      run: sudo apt install -y crystal libevent-dev libpcre2-dev libreadline-dev libssl-dev libyaml-dev

    - name: Install dependencies
      run: shards install

    - name: Run tests
      run: make test
